### ISSUE TITLE
Figure fix checklist

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/thesis#92]
This is an ever-growing list of fixes to make to figures:

- [x] @gillardjw pointed out the `+1e5` formatting in the histograms in the data analysis. Change to raw numbers or `10^5`.
- [x] Unify the x and y limits in the COPD model validation plots
- [x] Spacing in all of the EDO diagrams need adjusting (shouldn't `standalone` fix this?)
